server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8849
    gateway:
      routes:
        - id: userservice #路由标识， 必须唯一
          uri: lb://userservice #
          predicates:
            - Path=/user/**  # 路径断言，判断路径是否以/user开头，如果是则符合
        - id: orderservice
          uri: lb://orderservice
          predicates:
            - Path=/order/**


